services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_LOGIN}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
  frontend:
    image: cloud_file_storage_frontend
    container_name: cloud_file_storage_frontend
    restart: unless-stopped
    ports:
      - "8080:80"
  app:
    build: .
    image: cloud_file_storage
    container_name: cloud_file_storage_app
    restart: unless-stopped
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - redis
      - minio
      - frontend
    environment:
      POSTGRES_LOGIN: ${POSTGRES_LOGIN}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      MINIO_ACCESS_KEY: ${MINIO_LOGIN}
      MINIO_SECRET_KEY: ${MINIO_PASSWORD}
volumes:
  pgdata:
  redis_data:
  minio_data: