spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5433/users
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE
  session:
    timeout: 1h
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
springdoc:
  swagger-ui:
    path: /api/docs
    url: /documentation.yaml
  api-docs:
    enabled: true
minio:
  bucket-name: user-files