spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_LOGIN:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  jackson:
    property-naming-strategy: SNAKE_CASE
  session:
    timeout: 1h
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    redis:
      host: redis
springdoc:
  swagger-ui:
    path: /api/docs
    url: /documentation.yaml
  api-docs:
    enabled: true
minio:
  bucket-name: user-files
  endpoint: http://minio:9000
  access-key: ${MINIO_LOGIN:admin}
  secret-key: ${MINIO_PASSWORD:password}